### ISSUE TITLE
考虑做个 idea 系列的插件？

### ISSUE THREAD

**Issue by SeigeC** [whoiscc/shift-saver#1]
考虑做个 idea 系列的插件？

**Comment by whoiscc** [comment]
抱歉，没有支持IntelliJ Platform的计划，因为没有学习文档和开发维护的精力。

插件市场上有一款叫[CamelCase](https://plugins.jetbrains.com/plugin/7160-camelcase)的插件，也许可以实现类似的需求。

感谢建议。
