### ISSUE TITLE
Possible strategy dealing with Lisp/ML syntax.

### ISSUE THREAD

**Issue by DogLooksGood** [whoiscc/shift-saver#2]
Hey, I see your video on Bilibili and the switching strategy in this package looks interesting.

 I also trying to build something similar in Emacs, the problem I'm facing is that how to deal with Lisp/ML syntax. Lisp's code allows  `(a-b a-b a-b)` and ML's code allows `fooBar fooBar fooBar`. So if using whitespace as separator for words, there is no chance to exit before next symbol.

Any good ideas?

**Comment by whoiscc** [comment]
I would suggest using tab as exiting signal and convert it into a space character.

**Comment by DogLooksGood** [comment]
Good idea, thank you very much!
